services:
  httpd:
    image: etzion/centos-apache-php51:latest
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
    ports:
      - 8080:80

  http-cron:
    image: etzion/centos-apache-php51:latest
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./cron:./var/spool/cron
    command: >
      /usr/sbin/crond

